### ISSUE TITLE
Does not handle PIA forwarded port correctly

### ISSUE THREAD

**Issue by burningserenity** [BiglySoftware/BiglyBT-plugin-vpn_helper#2]
After about 45 minutes, the plugin fails to read the forwarded port. It is no longer necessary to parse the logs to grab that port, and the web API call stopped working in 2017.

PIA now has a CLI which can be used to get the port. Use `piactl get portforward` and it will return the correct number. See [here](https://www.privateinternetaccess.com/helpdesk/kb/articles/pia-desktop-command-line-interface) for more information.

**Comment by TuxPaper** [comment]
Thanks for bringing the CLI to my attention! I've been hoping for something like this for a long time, and will integrate it into the next plugin release.

Just for clarity, log scanning is just a fallback if their old RPC fails (`www.privateinternetaccess.com/vpninfo/port_forward_assignment` with credentials).  I believe they deprecated their old RPC years ago, but it still works a random amount of the time (if I had to guess, they probably time limited it to VPN connection start).  The advantage of the RPC is it can open a new port number just for BiglyBT (although we try to use the one they already opened).

Quick test of the CLI returns the open port on normal ip routing, but fails with network splitting (probably because the CLI assumes the default route goes through their VPN). Considering almost no one uses network splitting, the CLI will do wonderfully.

**Comment by TuxPaper** [comment]
ooh, they also have `piactl monitor portforward` for live monitoring which returns wonderful things like 
* Port Number
* "Inactive"
* "Attempting"
* "Failed"
* "Unavailable"

which I can use in the BiglyBT GUI  :D

**Comment by burningserenity** [comment]
Cool, I'm glad it's useful to you! I guess I should mention that I'm the lead QA engineer for PIA. By network splitting, do you perchance mean the split tunnel in PIA's settings?

**Comment by TuxPaper** [comment]
No, not the split tunnel feature (which is a great addition, btw) in PIA Manager.

I'm not sure if my phrase "Network Splitting" is technically correct, but it's basically the ability to have the VPN on, but no network traffic being routed to it, unless specifically doing so.  There's various howto's out there, but the gist of it (on windows) is to add routes that take precedence over the VPN's route.  Something like this is common on the tutorials: 

```
@route add   0.0.0.0 mask 192.0.0.0 %GATEWAY_GW% if %GATEWAY_IDX%
@route add  64.0.0.0 mask 192.0.0.0 %GATEWAY_GW% if %GATEWAY_IDX%
@route add 128.0.0.0 mask 192.0.0.0 %GATEWAY_GW% if %GATEWAY_IDX%
@route add 192.0.0.0 mask 192.0.0.0 %GATEWAY_GW% if %GATEWAY_IDX%
```

It's sort the split tunnel feature, except the opposite -- instead of all apps included in VPN with a list being excluded, it's all apps excluded with only apps that bind to the VPN's network interface, included.


It's popular for users who only want their torrent client (or any app that can bind to an network interface) to use the VPN, and everything else runs outside of the VPN.  For the paranoid, this gives them peace of mind that when they log into Facebook, their IP won't be the VPN's, which is being used to torrents.  A malicious site with personal information about the user could associate you with the activity on the VPN without a split.  ie. You are download a linux torrent using the VPN, and log onto a malicious site with the name "TuxPaper", and if the malicious site is also monitoring that torrent, it could make the association that "TuxPaper downloaded linux, what a perv".  You have to be extremely paranoid though to believe a popular site would be doing this (some of our users are that paranoid :P)

However, since the default traffic is no longer going through the VPN, the PIA Manager (and CLI) fail to grab the VPN IP or get an open port.  It's probably because the PIA Manager doesn't bind to the VPN's network interface to do the calls, it probably just assumes that unbound will be to the VPN (and it would be correct in almost all cases except this one)

It's not something to worry too much about, but if you have a dev's ear, maybe they can make sense of what I said and know of a way to fix it.  However, there might be a very good reason for not explicitly binding to the VPNs network interface, like something security related or some other unintended consequences.

**Comment by burningserenity** [comment]
Try upgrading to 1.8. PIA now binds those API calls to the tunnel interface. 1.8 also has an implementation of exactly what you're describing in that version's split tunnel. You can use it by setting "All Other Apps" to "Bypass VPN" and setting BiglyBT to "VPN Only."

**Comment by TuxPaper** [comment]
Looking forward to testing it out in the next few days.  We should have a plugin release using the CLI this week.

For everyone following this issue, the docs for Inverse Split Tunneling (allow any/all apps to bypass or use the VPN) is at https://www.privateinternetaccess.com/helpdesk/kb/articles/desktop-application-split-tunneling-feature

**Comment by TuxPaper** [comment]
Latest plugin version now uses PIA CLI. Users who upgrade to BiglyBT 2.3.0.0 or on beta will get new plugin automatically (if they have auto-update turned on)

Thanks for all your help @burningserenity
